import BannerComponent from '../../components/Banner/Banner'
import FooterComponent from '../../components/Footer/Footer'
import NavbarComponent from '../../components/Navbar/Navbar'
import './globals.css'


export const metadata = {
  title: 'API consumer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <NavbarComponent />
        <BannerComponent />
        {children}
        <FooterComponent />

      </body>

    </html>
  )
}
