import NavbarComponent from '../../components/Navbar/Navbar'
import './globals.css'


export const metadata = {
  title: 'API consumer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <NavbarComponent />
        {children}

      </body>

    </html>
  )
}
